version: "3.7"

services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    networks:
      - my-network

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge